version: '2'

services:
  web:
    build: ./app
    ports:
    - 8080:8080
    volumes:
    - ./app:/usr/src/app/:rw
    environment:
    - NODE_ENV=dev

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web
    depends_on:
      - web
